# -*- coding: utf-8 -*-
"""Data Cleaning Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhYy944EJI7g4xnmaJ5yAAWVS5jEkVHL

Setup & Install Libraries
"""

# Install required libraries (Google Colab — run once)
!pip install plotly duckdb scikit-learn --quiet

# Core imports
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import duckdb
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')

print('✅ All libraries loaded successfully!')

"""Load Datasets & First Look"""

df1 = pd.read_csv ('/content/1. Student Stress Factors and Mental Health.csv')
df2 = pd.read_csv ('/content/2. Student Stress Level.csv')

# Load first dataset
df_mental = pd.read_csv('/content/1. Student Stress Factors and Mental Health.csv')
print("Mental Health dataset shape:", df_mental.shape)
df_mental.head()

print('=' * 55)
print('📊 DATASET 1 — Stress Factors & Mental Health')
print('=' * 55)
print(f'Shape: {df1.shape[0]} rows × {df1.shape[1]} columns')
print()
print(df1.head())

print()
print('=' * 55)
print('📊 DATASET 2 — Stress Level Dataset')
print('=' * 55)
print(f'Shape: {df2.shape[0]} rows × {df2.shape[1]} columns')
print()
print(df2.head())

"""Column Names, Data Types & Missing Values"""

# ── Dataset 1 ─────────────────────────────────────────────────────────────
print('📋 DATASET 1 — Column Info')
print('-' * 50)
print(df1.dtypes)
print()
print('Missing values per column:')
print(df1.isnull().sum())
print(f'\nTotal missing values: {df1.isnull().sum().sum()}')

print()
print('📋 DATASET 2 — Column Info')
print('-' * 50)
print(df2.dtypes)
print()
print('Missing values per column:')
print(df2.isnull().sum())
print(f'\nTotal missing values: {df2.isnull().sum().sum()}')

# Unique values in categorical columns (Dataset 1)
cat_cols = ['Gender', 'Year Of Study', 'Cgpa', 'Depression', 'Anxiety', 'Panic Attack', 'Sought Treatment']

print('📊 Unique values in categorical columns (Dataset 1):')
print('-' * 50)
for col in cat_cols:
    print(f'{col:25s}: {df1[col].unique().tolist()}')

"""Descriptive Statistics"""

print('📊 DATASET 1 — Descriptive Statistics (Numerical Columns)')
print('=' * 65)
print(df1.describe().round(2).to_string())

print()
print('📊 DATASET 2 — Descriptive Statistics (All Numerical)')
print('=' * 65)
print(df2.describe().round(2).to_string())

# Value counts for Stress Level (both datasets)
print('📊 Stress Level Distribution — Dataset 1 (Scale 1–5):')
vc1 = df1['Stress Level'].value_counts().sort_index()
for level, count in vc1.items():
    bar = '█' * count
    print(f'  Level {level}: {bar} ({count})')

print()
print('📊 Stress Level Distribution — Dataset 2 (Binary 1=Low, 2=High):')
vc2 = df2['Stress Level'].value_counts().sort_index()
labels = {1: 'Low Stress', 2: 'High Stress'}
for level, count in vc2.items():
    bar = '█' * (count // 2)
    print(f'  {labels[level]:12s}: {bar} ({count})')